import Sidebar from "../components/Sidebar/Sidebar";
import Navbar from "../components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-row"> 
        <div className="fixed bg-opacity-95 md:hidden lg:flex">
          <Sidebar />
        </div>
        <div className="flex flex-col  lg:ml-[15.6rem] lg:border border-black lg:w-[83vw] rounded-[20px] h-[98vh] mt-3 fixed border-opacity-30 bg-gray-100 x-sm:ml-0">
          <div className="lg:fixed lg:w-[82.9vw] bg-white rounded-t-[1.2rem]  z-10 border-b-2 border-neutral-300 x-sm:w-[100vw] x-sm:flex  x-sm:rounded-b-[2rem] ">
            <Navbar />
          </div>
          <div className="lg:pt-[4%] md:pt-[3%] overflow-y-scroll x-sm:p-0 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
